const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { once } = require('node:events');
const express = require('express');
process.env.DATA_DIR = fs.mkdtempSync(path.join(os.tmpdir(), 'schema-ai-settings-'));
process.env.APP_SECRET = 'test-only-settings-secret';
process.env.OPENAI_API_KEY = 'environment-test-key';
delete process.env.GEMINI_API_KEY;
const store = require('../src/services/workspaceStore');

test('AI settings encrypt secrets, preserve blank keys, resolve defaults and expose no secrets through HTTP', async t => {
  const app = express(); app.use(express.json()); app.use('/api', require('../src/routes/workspaces'));
  const server = app.listen(0, '127.0.0.1'); await once(server, 'listening');
  t.after(() => { server.closeAllConnections(); server.close(); });
  const url = `http://127.0.0.1:${server.address().port}/api/settings/ai`;
  const response = await fetch(url, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ defaultProvider: 'gemini', providers: { gemini: { apiKey: 'private-test-key-123', model: 'model-test' } } }) });
  assert.equal(response.status, 200);
  assert.equal(response.headers.get('cache-control'), 'no-store');
  assert.doesNotMatch(await response.text(), /private-test-key-123/);
  const settings = (await (await fetch(url)).json()).settings;
  assert.equal(settings.providers.gemini.hasSavedKey, true);
  assert.equal(settings.providers.openai.hasEnvironmentKey, true);
  const disk = fs.readFileSync(path.join(process.env.DATA_DIR, 'workspace.json'), 'utf8');
  assert.doesNotMatch(disk, /private-test-key-123/); assert.match(disk, /v1:/);
  assert.deepEqual(store.resolveAIOptions(), { provider: 'gemini', apiKey: 'private-test-key-123', model: 'model-test' });
  store.saveAISettings({ providers: { gemini: { apiKey: '' } } });
  assert.equal(store.resolveAIOptions().apiKey, 'private-test-key-123');
  assert.equal(store.resolveAIOptions({ apiKey: 'request-key' }).apiKey, 'request-key');
  assert.equal(store.resolveAIOptions({ model: 'selected-model-override' }).model, 'selected-model-override');
  assert.equal(store.resolveAIOptions({ provider: 'openai' }).apiKey, 'environment-test-key');
  store.saveAISettings({ providers: { gemini: { removeKey: true } } });
  assert.throws(() => store.resolveAIOptions(), /Save an API key/);
  assert.throws(() => store.saveAISettings({ defaultProvider: 'unknown' }), /Unsupported/);
  assert.equal((await fetch(url, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ providers: { openai: { apiKey: 'bad key' } } }) })).status, 400);
  store.saveAISettings({ providers: { gemini: { apiKey: 'saved-generation-test-key' } } });
  const schemas = require('../src/services/pageSchema');
  const original = schemas.generateAI;
  t.after(() => { schemas.generateAI = original; });
  let received;
  schemas.generateAI = async (page, options) => { received = options; return schemas.generate(page); };
  const site = store.createSite({ name: 'AI integration test', url: 'https://example.test' });
  const run = store.createRun(site.id);
  const page = { url: 'https://example.test/about', title: 'About us', content: 'We publish books.' };
  store.updateRun(run.id, { status: 'ready', pages: [{ url: page.url, pageData: page }] });
  const generateUrl = `http://127.0.0.1:${server.address().port}/api/runs/${run.id}/generate`;
  assert.equal((await fetch(generateUrl, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ urls: [page.url], useAI: false }) })).status, 202);
  for (let i = 0; i < 100 && store.getRun(run.id).status === 'generating'; i++) await new Promise(resolve => setTimeout(resolve, 10));
  assert.equal(store.getRun(run.id).status, 'completed');
  assert.equal(received.apiKey, 'saved-generation-test-key');
  assert.equal(received.model, 'model-test');
  assert.equal(store.getRun(run.id).pages[0].generation.engine, 'ai', 'AI remains mandatory even when a client sends useAI:false');
  assert.doesNotMatch(JSON.stringify(store.getRun(run.id)), /saved-generation-test-key/);
});
