const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const express = require('express');
const { once } = require('node:events');
process.env.DATA_DIR = fs.mkdtempSync(path.join(os.tmpdir(), 'schema-auth-test-'));
process.env.PUBLIC_URL = 'http://localhost:3000';
const auth = require('../src/services/authStore');
const authentication = require('../src/auth');

test('private login protects UI/API, requires same-origin CSRF, revokes and expires sessions', async t => {
  const app = express();
  app.set('views', path.join(__dirname, '../src/views')); app.set('view engine', 'ejs');
  app.use(express.urlencoded({ extended: false })); app.use(express.json()); app.use(authentication());
  app.get('/health', (req, res) => res.json({ status: 'ok' }));
  app.get('/', (req, res) => res.json({ user: req.auth.username, csrf: req.auth.csrf }));
  app.get('/api/private', (req, res) => res.json({ secret: true }));
  app.post('/api/private', (req, res) => res.json({ saved: true }));
  const server = app.listen(0, '127.0.0.1'); await once(server, 'listening');
  t.after(() => { server.closeAllConnections(); server.close(); });
  const base = `http://127.0.0.1:${server.address().port}`;
  const call = (url, options = {}) => fetch(base + url, { redirect: 'manual', ...options });
  const login = (password, origin = 'http://localhost:3000') => call('/login', { method: 'POST', headers: { 'Content-Type': 'application/json', Origin: origin }, body: JSON.stringify({ username: 'admin', password }) });
  assert.equal((await call('/health')).status, 200);
  assert.equal((await call('/')).status, 303);
  assert.equal((await call('/api/private')).status, 401);
  assert.match(await (await call('/login')).text(), /Set up your administrator/);
  await assert.rejects(auth.setUser('admin', 'short'));
  await assert.rejects(auth.setUser('admin', '12345678'), /9–256/);
  await auth.setUser('admin', '123456789');
  assert.equal(await auth.verify('admin', '123456789'), true);
  const password = 'fixture-only-long-password';
  await auth.setUser('admin', password);
  assert.ok(!fs.readFileSync(path.join(process.env.DATA_DIR, 'auth.json'), 'utf8').includes(password));
  assert.equal((await login(password, 'https://evil.example')).status, 403);
  assert.equal((await login('incorrect-password')).status, 401);
  const signedIn = await login(password); assert.equal(signedIn.status, 303);
  const setCookie = signedIn.headers.get('set-cookie');
  assert.match(setCookie, /HttpOnly/); assert.match(setCookie, /SameSite=Strict/);
  const cookie = setCookie.split(';')[0];
  const current = await (await call('/', { headers: { Cookie: cookie } })).json();
  assert.equal(current.user, 'admin');
  const headers = { Cookie: cookie, Origin: 'http://localhost:3000', 'X-CSRF-Token': current.csrf };
  assert.equal((await call('/api/private', { method: 'POST', headers })).status, 200);
  assert.equal((await call('/api/private', { method: 'POST', headers: { Cookie: cookie, Origin: 'http://localhost:3000' } })).status, 403);
  assert.equal((await call('/api/private', { method: 'POST', headers: { ...headers, Origin: 'https://evil.example' } })).status, 403);
  assert.equal((await call('/logout', { method: 'POST', headers })).status, 303);
  assert.equal((await call('/api/private', { headers: { Cookie: cookie } })).status, 401);
  const session = auth.createSession();
  assert.ok(auth.session(session.token));
  assert.ok(!fs.readFileSync(path.join(process.env.DATA_DIR, 'auth.json'), 'utf8').includes(session.token));
  const stored = JSON.parse(fs.readFileSync(path.join(process.env.DATA_DIR, 'auth.json')));
  stored.sessions[0].expires = 1; fs.writeFileSync(path.join(process.env.DATA_DIR, 'auth.json'), JSON.stringify(stored));
  assert.equal(auth.session(session.token), null);
  const prior = auth.createSession();
  await auth.setUser('admin', 'another-fixture-password');
  assert.equal(auth.session(prior.token), null);
  for (let i = 0; i < 10; i++) assert.equal((await login('wrong')).status, 401);
  assert.equal((await login('wrong')).status, 429);
});

test('cloud origin requires HTTPS and a strong encryption secret', () => {
  process.env.PUBLIC_URL = 'http://schema.example.com';
  assert.throws(authentication, /HTTPS/);
  process.env.PUBLIC_URL = 'https://schema.example.com';
  delete process.env.APP_SECRET;
  assert.throws(authentication, /APP_SECRET/);
  process.env.APP_SECRET = 'a-test-only-secret-with-at-least-32-characters';
  assert.doesNotThrow(authentication);
  process.env.PUBLIC_URL = 'http://localhost:3000';
});
